docker run -ti \
  -eQUARKUS_DATASOURCE_USERNAME="${QUARKUS_DATASOURCE_USERNAME}" \
  -eQUARKUS_DATASOURCE_PASSWORD="${QUARKUS_DATASOURCE_PASSWORD}" \
  -eQUARKUS_DATASOURCE_JDBC_URL="${QUARKUS_DATASOURCE_JDBC_URL}" \
  -p13372:13372 \
  caravanacloud/piggybank:latest
